version: "3.8"

services:
  app:
    build: .
    ports:
      - "2508:2508"
    volumes:
      - .:/app
      - ./emotiondetection-743bb-firebase-adminsdk-fbsvc-24aba711a6.json:/app/emotiondetection-743bb-firebase-adminsdk-fbsvc-24aba711a6.json
    env_file:
      - .env
    environment:
      - PORT=2508
      - FIREBASE_SERVICE_ACCOUNT_KEY=/app/emotiondetection-743bb-firebase-adminsdk-fbsvc-24aba711a6.json
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 2508 --reload
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
