version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "443:443"  # HTTPS port
      - "2508:2508" # HTTP port (optional, for redirection)
    volumes:
      - .:/app
      - ./emotiondetection-743bb-firebase-adminsdk-fbsvc-24aba711a6.json:/emotiondetection-743bb-firebase-adminsdk-fbsvc-24aba711a6.json
      - ./ssl:/app/ssl  # Mount SSL certificates
    env_file:
      - .env.prod
    environment:
      - PORT=443
      - SSL_KEYFILE=/app/ssl/key.pem
      - SSL_CERTFILE=/app/ssl/cert.pem
      - HTTPS_ENABLED=true
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 443 --ssl-keyfile /app/ssl/key.pem --ssl-certfile /app/ssl/cert.pem
    networks:
      - app-network

networks:
  app-network:
    driver: bridge