version: "3.8"

services:
  app:
    build: .
    ports:
      - "2508:2508"
    volumes:
      - .:/app
      - ./emotiondetection-743bb-firebase-adminsdk-fbsvc-24aba711a6.json:/emotiondetection-743bb-firebase-adminsdk-fbsvc-24aba711a6.json
    env_file:
      - .env
    environment:
      - PORT=2508
      - WATCHFILES_FORCE_POLLING=true 
      - WATCHFILES_POLL_INTERVAL=0.5 
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 2508 --reload --reload-include *.py --reload-include *.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
